apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-access-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  kind: Role
  name: node-access-role
  apiGroup: rbac.authorization.k8s.io
